### ISSUE TITLE
Cannot find module 'components/utils/prop-types'

### ISSUE THREAD

**Issue by terrainwax** [geist-org/react#425] opened 2020-12-13 00:52 UTC
# Bug report 🐞

## Version & Environment

  - Chrome 87.0.4280.88
  - 2.0.3

## Expection

Component working on react typescript

## Actual results (or Errors)

 ERROR in F:/Nouveau dossier (5)/CrewLink/node_modules/@geist-ui/react/dist/input/input-props.d.ts(2,40):
  TS2307: Cannot find module 'components/utils/prop-types' or its corresponding type declarations.
  ERROR in F:/Nouveau dossier (5)/CrewLink/node_modules/@geist-ui/react/dist/loading/loading.d.ts(2,42):
  TS2307: Cannot find module 'components/utils/prop-types' or its corresponding type declarations.
  ERROR in F:/Nouveau dossier (5)/CrewLink/node_modules/@geist-ui/react/dist/progress/progress.d.ts(2,29):
  TS2307: Cannot find module 'components/utils/prop-types' or its corresponding type declarations.
  ERROR in F:/Nouveau dossier (5)/CrewLink/node_modules/@geist-ui/react/dist/radio/radio-group.d.ts(2,29):
  TS2307: Cannot find module 'components/utils/prop-types' or its corresponding type declarations.
  ERROR in F:/Nouveau dossier (5)/CrewLink/node_modules/@geist-ui/react/dist/styles/theme-provider/theme- 
  provider.d.ts(3,29):
  TS2307: Cannot find module '../../utils/types' or its corresponding type declarations.

**Comment by unix** [comment] 2020-12-31 03:21
This is caused by the type reference path, but the package does not recognize the alias, I am in the process of fixing.

**Comment by PaulPCIO** [comment] 2021-01-24 23:31
+1 on this

**Comment by unix** [comment] 2021-02-18 02:44
fixed in the latest.

**Closed by unix** 2021-02-18 02:44 UTC
Labels: bug
