### ISSUE TITLE
Custom theme on Dark Mode is getting override to it's default.

### ISSUE THREAD

**Issue by NamanGangwar** [geist-org/react#436] opened 2021-01-25 03:53 UTC
# Bug report 🐞

## Version & Environment

  - Chrome 87.0.4280.141
  - 2.0.3

## Expection
Layout should have the width as it's mentioned in the GeistProvider theme object (pageWidth).

## Actual results (or Errors)
When using the darkTheme object, the page layout gets reset to the default pageWidth (750pt) instead of (1000pt). It works fine when you use lightTheme object.

_app.js:

```
import { GeistProvider, CssBaseline } from "@geist-ui/react";

const darkTheme = {
  type: "dark",
  layout: {
    pageWidth: "1000pt"
  }
};

const lightTheme = {
  type: "light",
  layout: {
    pageWidth: "1000pt"
  }
};

const MyApp = ({ Component, pageProps }) => {
  return (
    <GeistProvider theme={darkTheme}>
      <CssBaseline />
      <Component {...pageProps} />
    </GeistProvider>
  );
};

export default MyApp;

```
index.js:
```
import React from "react";
import { Page } from "@geist-ui/react";

const HomePage = (props) => {
  return (
    <Page>
      <Page.Header>
        <h2>Header</h2>
      </Page.Header>
      <Page.Content>
        <h2>Hello, Everyone.</h2>
        <p>This is a simulated page, you can click anywhere to close it.</p>
      </Page.Content>
      <Page.Footer>
        <h2>Footer</h2>
      </Page.Footer>
    </Page>
  );
};

export default HomePage;
```

**Comment by scitronboy** [comment] 2021-01-28 04:57
Yep, this is happening for me too. It seems it ignores any other custom theme options when the type is set to dark.

**Comment by scitronboy** [comment] 2021-01-28 05:10
I believe the problem is [this line](https://github.com/geist-org/react/blob/99b602787e5c7c0ee4b7ffb9b2687d20ca7d6f77/components/styles/theme-provider/theme-provider.tsx#L62). It seems when switching to dark theme it overrides the entire theme. The solution would be to override the dark theme with the user theme instead. Working on a PR now....

**Comment by scitronboy** [comment] 2021-01-28 05:54
Doing this seems to work - however it would probably be a breaking change, as many websites (including the official one) have a custom theme that only works with light theme. In the case of the official website, when the theme is changed it is always [merged with the default theme](https://github.com/geist-org/react/blob/99b602787e5c7c0ee4b7ffb9b2687d20ca7d6f77/lib/config-provider.tsx#L33) ([from the useTheme hook](https://github.com/geist-org/react/blob/99b602787e5c7c0ee4b7ffb9b2687d20ca7d6f77/components/styles/use-theme/use-theme.ts#L5), which is set to the light theme and never changed) thus the site only works properly if the custom theme is overwritten in dark mode. Although, I haven't studied the code for very long at all so correct me if I'm misunderstanding how this works.

 So, to prevent this from breaking anything I propose the adding another optional property to the custom theme object called `darkTheme`, which will be merged with the dark theme (if present). This will allow the dark theme to be customized without breaking any websites. 

Additionally, the website needs to be changed as well so that it works properly with the theming system but I'll probably leave that to a future PR.

Let me know if you have any thoughts.

**Comment by michaelwschultz** [comment] 2021-01-29 23:31
I'm having a similar issue while using the dark theme. I have a custom palette that overrides the `light` theme just fine. However, which switching to the `dark` theme my palette is no longer overriding the default palette.

``` JSX
const customPalette: Partial<GeistUIThemesPalette> = {
  success: '#FF062C',
}

const [themeType, setThemeType] = useState('dark')

<GeistProvider theme={{ type: themeType, palette: customPalette }}>
```

**Comment by scitronboy** [comment] 2021-01-30 02:39
I think we should probably rewrite the theme system entirely to make it simpler and more flexible (including support for more than two themes); but for now it looks like we're just waiting for unix's say

**Comment by NamanGangwar** [comment] 2021-01-30 16:11
> I think we should probably rewrite the theme system entirely to make it simpler and more flexible (including support for more than two themes); but for now it looks like we're just waiting for unix's say

That'll be great, Let's see what Unix thinks about this.

**Comment by unix** [comment] 2021-01-30 17:17
This is my initial design mistake, the `theme=` can't solve the two goals of switching themes and customizing themes at the same time. there was an identical proposal some time ago: #353 .
I've been busy with my own work lately, but I'll work on refactoring the theme module and I'll follow up by creating a PR .

**Comment by unix** [comment] 2021-01-30 17:42
I came up with several options earlier, but now that I look back at these ideas, I think there is one that is very simple and easy to use:
  - Use `themes={[]}` to define the list of `theme`, you can define as much content as you want, the missing parts will be filled in automatically.
  - Each `theme` must contain at least the type attribute as an identifier: `myTheme = { type: string, others ... }`
  - You can inherit other people's themes or the default two themes (`light / dark`) as you wish.
  - **Switching themes can only be done through `themeType={string}`**

----
In terms of details, the following features are perfectly feasible:
  - The type of `themeType=` can be automatically deduced from the `theme` you fill in:
  
  ```ts
const myTheme = { type: 'myTheme', others... }

// The type of themeType  -> 'dark' | 'light' | 'myTheme'
// There will be automatic constraints here
<GeistProvider themes={[myTheme]} themeType={'...'}>
   ```

  - You can inherit a new theme you need from `light` or `dark`, or even a theme for others in the community:

```ts
const myDarkTheme = Theme.merge(DEFAULT_DARK_THEME, { type: 'myDarkTheme', others ... })
```

----

I'll be thinking about and writing the code here in the next few days, If you have any suggestions, please feel free to continue to comment.

**Comment by michaelwschultz** [comment] 2021-01-30 18:32
This would be amazing! Thanks so much @unix. This project is so well done and so well documented. Appreciate all the work you've put in.

**Comment by unix** [comment] 2021-02-14 09:19
The new theme system has been released, use `yarn add @geist-ui/react@latest` to try it out, and the documentation has been updated.

**Closed by unix** 2021-02-14 09:19 UTC

**Comment by michaelwschultz** [comment] 2021-02-15 18:04
I'll check it out today! Thanks so much @unix.

**Comment by scitronboy** [comment] 2021-02-18 07:27
Ooh thank you very much, I appreciate it! Thanks for the awesome library!
